### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by boxdl** [Peckot-Studios/PremiumCheck#1]
有个很严重的问题：在线模式下，玩家的uuid是没有变化的，自然而然认证也就没问题
但是在离线模式下，正版玩家的uuid和登录到服务器上的uuid是不相同的，最终导致认证失败！

**Comment by Pectix** [comment]
实际上这个插件对未使用YggdrasilOfficialProxy的服务器完全无效。

如果服务器为online mode，那么所有玩家均为正版，无需本插件进行验证；
如果服务器为offline mode，所有玩家的uuid均为加入时随机生成，无法进行正版验证。

YOP实现了对外置登录的扩展。在传统的外置登录服务器，客户端只能使用外置登录加入服务器（而正版或是离线模式均无法加入）。而YOP所实现的功能是让外置登录与正版登录并存（离线模式仍然无法加入），使得正版玩家加入游戏的uuid为正版id，而外置登录玩家uuid获取方式为皮肤站后台所设置的模式。只有在这种情况下才可以通过联网uuid验证实现正版验证。

对于正版服务器服主，您完全没有必要使用本插件；
对于离线服务器服主，您可以使用其他利用邮箱和密码进行验证的插件实现您的功能期望。
